CREATE TABLE PRODUCTO(
                         ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
                         nombre varchar(100),
                         fecha_registro date,
                         primary key(id)
);

create or replace PROCEDURE SP_PRODUCTO_INSERT(nombre varchar, fecharegistro date, pcursor out sys_refcursor, pcodigo out varchar, mensaje out varchar)
as
BEGIN
BEGIN
INSERT INTO PRODUCTO (nombre, fecha_registro)
VALUES (nombre, fecharegistro)
    RETURNING ID INTO pcodigo;
commit;

pcodigo := '000';
       mensaje := 'Registro Exitoso';

EXCEPTION
        WHEN OTHERS THEN
            pcodigo:='001';
            mensaje := 'ERROR AL REGISTRAR EL PRODUCTO: ' || SQLERRM;
        RETURN;
END;

open pcursor for
Select id,nombre, fecha_registro from producto where to_date(fecha_registro,'dd/mm/yyyy') = to_date(fecharegistro,'dd/mm/yyyy') order by id;
END;